### ISSUE TITLE
Additional relay-node implementation guide

### ISSUE THREAD

**Issue by carte731** [jaxa/roscfe#2]
Hello, 

I was wondering if you could create or share additional implementation guides on relay_node. I'm trying to implement some basic ROS movement and video capture through roscFE on a Gazebo simulation.

I'm a little lost on how to use the custom roscFE libraries to do this.

Thanks,
Corey C.

**Comment by yuyuqq** [comment]
Hi Corey,
While writing the user guide, we have found that the procedure for using ROS/cFE bridge not intuitive. Let us fix it; then we will upload the guide. Thanks!

**Comment by yuyuqq** [comment]
Hi Corey,
We updated the documentation while we made the ROS/cFE bridge acts simpler. Please let us know how you think. Thanks!

**Comment by kbiesiadecki141** [comment]
Hi, I didn't see any updated documentation - can you point me to it? Looks like there is a tutorials directory with some example nodes, but is there a guide for walking through that tutorial? 

Thanks again for the help!

**Comment by carte731** [comment]
Thank you, I'll read through it this week!

**Comment by carte731** [comment]
> Hi, I didn't see any updated documentation - can you point me to it? Looks like there is a tutorials directory with some example nodes, but is there a guide for walking through that tutorial?
> 
> Thanks again for the help!

kbiesiadecki141 the examples are located in the github repo's wiki (here's a link):
https://github.com/jaxa/roscfe/wiki
