### ISSUE TITLE
Missing Tutorial Files for cFS Build

### ISSUE THREAD

**Issue by NMPatel06** [jaxa/roscfe#5]
I was following along with several of the tutorials and it looks like there are several missing files that were called out to copy over to the cFS location.  Looking at example 4, step 9 and 10 call for copying the Makefile and cfe_es_startup.scr files from the tutorial directory in the repo.  I was able to create my own, but it would be nice to be able to follow the tutorial all the way through and compare the files.

**Comment by yuyuqq** [comment]
Hi there,
Thank you for your comment. We added the example files as suggested. Please let us know how the tutorial helps.  Thank you!
